[package]
name = "rakaly"
version = "0.0.2"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
eu4save = "0.3"
imperator-save = "0.1"
ck3save = "0.1"
argh = "0.1"
memmap = "0.7"
anyhow = "1"

[dev-dependencies]
attohttpc = "0.16"
assert_cmd = "1"
native-tls = { version = "0.2", features = ["vendored"] }

[profile.release]
lto = "thin"
