[package]
name = "rakaly"
version = "0.0.1"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
eu4save = "0.3"
imperator-save = "0.1"
ck3save = "0.1"
argh = "0.1"
memmap = "0.7"
anyhow = "1"

[dev-dependencies]
rust-s3 = "0.26"
assert_cmd = "1"
predicates = "1"
tempfile = "3"

[profile.release]
lto = "thin"
