[package]
name = "rakaly"
version = "0.4.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
jomini = "0.19"
eu4save = "0.7"
imperator-save = "0.3"
ck3save = "0.3"
hoi4save = "0.2"
argh = "0.1"
memmap = "0.7"
anyhow = "1"
brotli = "3"
attohttpc = { version = "0.19", features = ["json"] }
native-tls = { version = "0.2", features = ["vendored"] }
serde = { version = "1",   features = ["derive"] }
toml = "0.5"
directories = "4"
base64 = "0.13"
fern = "0.6"
log = "0.4"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
tar = "0.4"


[dev-dependencies]
assert_cmd = "2"

[profile.release]
lto = "thin"
