name: ci
on:
  push:
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      TARGET:
    strategy:
      fail-fast: false
      matrix:
        build:
        - linux-musl
        - macos
        - win-msvc
        include:
        - build: linux-musl
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-latest
          target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - name: Cache saves
      uses: actions/cache@v2
      with:
        path: assets/saves
        key: assets/saves
    - name: Decrypt tokens
      run: ./assets/ci/decrypt_secret.sh
      env:
        TOKEN_PASSPHRASE: ${{ secrets.TOKEN_PASSPHRASE }}
    - name: Set cross environment variables
      if: matrix.build != 'macos' && matrix.build != 'win-msvc'
      run: |
        echo "EU4_IRONMAN_TOKENS=/project/assets/tokens/eu4.txt" >> $GITHUB_ENV
        echo "CK3_IRONMAN_TOKENS=/project/assets/tokens/ck3.txt" >> $GITHUB_ENV
        echo "IMPERATOR_TOKENS=/project/assets/tokens/imperator.txt" >> $GITHUB_ENV
    - name: Set cargo environment variables
      if: matrix.build == 'macos' || matrix.build == 'win-msvc'
      shell: bash
      run: |
        echo "EU4_IRONMAN_TOKENS=$current_dir/assets/tokens/eu4.txt" >> $GITHUB_ENV
        echo "CK3_IRONMAN_TOKENS=$current_dir/assets/tokens/ck3.txt" >> $GITHUB_ENV
        echo "IMPERATOR_TOKENS=$current_dir/assets/tokens/imperator.txt" >> $GITHUB_ENV
      env:
        current_dir: ${{ github.workspace }}
    - name: Install Cross
      if: matrix.build != 'macos' && matrix.build != 'win-msvc'
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET=--target ${{ matrix.target }}" >> $GITHUB_ENV
    - name: Check work
      run:
        echo "CARGO=${{ env.CARGO }}"
        echo "TARGET=${{ env.TARGET }}"
        echo "EU4_IRONMAN_TOKENS=${{ env.EU4_IRONMAN_TOKENS }}"
        echo "CK3_IRONMAN_TOKENS=${{ env.CK3_IRONMAN_TOKENS }}"
        echo "IMPERATOR_TOKENS=${{ env.IMPERATOR_TOKENS }}"
    - name: Build
      run: ${{ env.CARGO }} build --verbose $TARGET
    - name: Test
      run: ${{ env.CARGO }} test --verbose $TARGET