name: ci
on:
  push:
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      TARGET:
    strategy:
      matrix:
        build:
        - linux-musl
        - macos
        - win-msvc
        include:
        - build: linux-musl
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - build: macos
          os: macos-latest
        - build: win-msvc
          os: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Decrypt tokens
      run: ./.github/scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - name: Set environment variables
      run: |
        echo "EU4_IRONMAN_TOKENS=./assets/tokens/eu4.txt" >> $GITHUB_ENV
        echo "CK3_IRONMAN_TOKENS=./assets/tokens/ck3.txt" >> $GITHUB_ENV
        echo "IMPERATOR_TOKENS=./assets/tokens/imperator.txt" >> $GITHUB_ENV
    - name: Use Cross
      if: matrix.target != ''
      run: cargo install cross
    - name: Build
      run: ${{ env.CARGO }} build --verbose $TARGET
    - name: Test
      run: ${{ env.CARGO }} test --verbose $TARGET